# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "objcViper" do
       pod "AFNetworking", "~> 2.0"
       pod "Mantle"
end 

target "objcViperTests" do
       pod 'Specta',      '~> 0.2.1'	
       pod 'Expecta',     '~> 0.2.3'   # expecta matchers
       pod 'OCMock',      '~> 2.2.1'   # OCMock
end

